### ISSUE TITLE
Error while parsing package [ ... ] (skipping)

### ISSUE THREAD

**Issue by milosivanovic** [realiti4/pip-upgrade#16]
I am getting this while running `pip-upgrade`. It is handling the error gracefully, but the update for pytz is being skipped.

```
Error while parsing package pytz==2023.3 (skipping).
Exception:  Invalid version: '2004d'
```

**Comment by realiti4** [comment]
Hi,

That error looks different than what we have in code. Maybe packaging library generates it? Could you share the full output please? A requirements.txt from the env you are trying to upgrade would help too. 

Also is it true that you are trying to upgrade pytz from 2004d, because it looks like that version is released in 2004.

**Comment by milosivanovic** [comment]
Sorry, the upgrade software I was using was [pip-upgrade](https://pypi.org/project/pip-upgrade/). Your repository seems to be `pip-upgrade-tool` which is a different piece of software. Apologies for the noise.

**Comment by realiti4** [comment]
No problem at all. Please feel free to try this repo as well if it meets your needs.
